-- ====================================================================
-- DRIED SEAFOOD GLOBAL — D1 INITIAL SEED DATA
-- Migration: 0002_seed_initial_data.sql
-- ====================================================================

-- 1. SEED PRODUCTS
INSERT OR IGNORE INTO products (
  id, name, name_ar, name_zh, latin_name, indonesian_name, slug, sku, category, hs_code, origin, origin_en, origin_ar,
  specification, supply_capacity, supply_capacity_en, supply_capacity_ar, certifications, key_markets, image_url, gallery_images,
  description, description_en, description_ar, short_description, price_usd_per_kg, price_idr_per_kg, moq_kg,
  status, is_published, featured, meta_title, meta_description, canonical_url, og_image_url, created_at, updated_at
) VALUES 
(
  'exp-teri-nasi',
  'Super White Anchovy / Teri Nasi Belawan Grade AAA',
  'أنشوجة بيضاء مجففة فائقة الجودة درجة أأأ',
  '白公鱼干 / 顶级无盐银鱼干',
  'Stolephorus commersonnii',
  'Ikan Teri Nasi Super Putih & Teri Medan Asli',
  'super-white-anchovy-teri-nasi',
  'DSG-PROD-001',
  'Ikan Teri & Bilis Kering',
  '0305.59.90',
  'Belawan (Sumatera Utara), Tuban & Pasuruan (Jawa Timur)',
  'Belawan (North Sumatra) & East Java Coast, Indonesia',
  'بيلاوان (شمال سومطرة) وساحل جاوة الشرقية، إندونيسيا',
  '{"grade":"Super AAA Grade (Ukuran 1.5 - 2.5 cm, Utuh & Putih Bersih)","moisture":"10% - 12% Max (Kadar Garam 2% - 4% Low Salt)","packaging":"100g/250g/500g Vacuum Pouch / 10 Kg Master Carton Box","moq":"500 Kg (LCL) / 1 x 20ft FCL (12 Metric Tons)","shelfLife":"12 Bulan dalam suhu ruang kering / 24 Bulan chiller","colorTexture":"Putih Gading Alami, Renyah, Non-Formalin, Bebas Pemutih"}',
  '80 Metrik Ton / Bulan',
  '80 Metric Tons / Month',
  '80 طن متري / شهر',
  '["HACCP Grade A","Health Certificate BKIPM","SKP KKP RI","Halal BPJPH","US FDA Registered"]',
  '["Hong Kong","Singapura","Taiwan","Malaysia","Amerika Serikat (USA)"]',
  '/images/products/exp-teri-nasi-1.png',
  '["/images/products/exp-teri-nasi-1.png","/images/products/exp-teri-nasi-2.png"]',
  'Ikan teri nasi kualitas super grade yang dikeringkan secara higienis menggunakan teknologi pengering modern. Berwarna putih gading alami tanpa bahan kimia pemutih, bercita rasa gurih renyah, dan sangat digemari pasar Asia Timur serta supermarket diaspora.',
  'Export-grade super white anchovy dried hygienically using modern solar dome technology. Natural ivory white color without bleaching chemicals, crispy and savory taste.',
  'أنشوجة بيضاء فاخرة مجففة بتقنيات حديثة وصحية، لون عاجي طبيعي دون مبيضات، نكهة مقرمشة وغنية تلبي معايير التصدير العالمية.',
  'Super AAA Grade White Anchovy from Belawan & Java Sea.',
  8.5,
  135000,
  500,
  'published',
  1,
  1,
  'Super White Anchovy Grade AAA Exporter | Dried Seafood Global',
  'Indonesian super white anchovy supplier. Pure sun-dried and solar dome processed, 0% formalin, HACCP certified.',
  'https://www.driedseafoodglobal.com/products/super-white-anchovy-teri-nasi',
  '/images/products/exp-teri-nasi-1.png',
  '2026-01-10T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'exp-ikan-jambal',
  'Salted Dried Giant Catfish Fillet (Ikan Asin Jambal Roti)',
  'فيليه سمك القرموط العملاق المملح والمجفف (جامبال روتي)',
  '巨鲶咸鱼柳 / 顶级面包香咸鱼',
  'Arius thalassinus',
  'Ikan Asin Jambal Roti Super Gurih Khas Pangandaran & Cilacap',
  'salted-dried-giant-catfish-jambal-roti',
  'DSG-PROD-002',
  'Ikan Asin Olahan Tradisional',
  '0305.59.20',
  'Pangandaran (Jawa Barat), Cilacap (Jawa Tengah), & Muara Angke (Jakarta)',
  'Pangandaran, Cilacap & Jakarta Port, Indonesia',
  'بانغانداران وتشيلاكاب وميناء جاكرتا، إندونيسيا',
  '{"grade":"Super Roti Premium (Daging Tebal Merekah / Empuk Seperti Roti)","moisture":"18% - 22% (Semi-Dry Cured Fillet)","packaging":"Vacuum Sealed Individually (500g - 1kg) + 20 Kg Master Box","moq":"1 x 20ft FCL (14 Metric Tons) / 1.000 Kg LCL","shelfLife":"8 Bulan dalam suhu ruang / 18 Bulan suhu sejuk","colorTexture":"Daging Cokelat Keemasan, Tekstur Lembut, Bebas Formalin"}',
  '60 Metrik Ton / Bulan',
  '60 Metric Tons / Month',
  '60 طن متري / شهر',
  '["HACCP Grade A","Health Certificate KKP","SKP KKP RI","Halal BPJPH"]',
  '["Singapura","Malaysia","Brunei Darussalam","Australia","Belanda"]',
  '/images/products/exp-ikan-a-1.png',
  '["/images/products/exp-ikan-a-1.png","/images/products/exp-ikan-a-2.png","/images/products/exp-ikan-a-3.png"]',
  'Dibuat dari ikan manyung liar segar pilihan dengan proses fermentasi garam alami tradisional. Daging tebal yang merekah lembut saat digoreng menyerupai tekstur roti, menjadikannya primadona kuliner ikan asin khas Indonesia berkelas ekspor.',
  'Premium cured giant catfish fillet with soft bread-like texture upon cooking, traditional natural sea salt fermentation.',
  'فيليه سمك جامبال روتي التقليدي المعالج بملح البحر الطبيعي، لحم سميك وشهي بقوام ناعم.',
  'Traditional Premium Salted Catfish Fillet.',
  9.2,
  145000,
  1000,
  'published',
  1,
  1,
  'Indonesian Salted Dried Catfish Jambal Roti Exporter',
  'Direct exporter of Indonesian Jambal Roti salted fish fillet. Thick cut, golden brown texture, HACCP certified.',
  'https://www.driedseafoodglobal.com/products/salted-dried-giant-catfish-jambal-roti',
  '/images/products/exp-ikan-a-1.png',
  '2026-01-10T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'exp-cumi-kering',
  'Sun-Dried Squid & Loligo Baby Cuttlefish',
  'حبار مجفف بالشمس وحبار لوليجو صغير',
  '日晒天然干鱿鱼 / 幼体枪乌贼干',
  'Loligo chinensis / Sepioteuthis lessoniana',
  'Cumi Kering Sero Pilihan & Baby Cumi Kering Super',
  'sun-dried-squid-baby-cuttlefish',
  'DSG-PROD-003',
  'Cumi & Sotong Kering',
  '0307.49.20',
  'Bangka Belitung, Tegal (Jawa Tengah), & Laut Jawa',
  'Bangka Belitung Islands & Java Sea, Indonesia',
  'جزر بانغكا بليتونغ وبحر جاوة، إندونيسيا',
  '{"grade":"Premium Grade A (Ukuran 4-6 cm Baby Cumi & 12-18 cm Cumi Sero)","moisture":"14% - 16% Max","packaging":"Vacuum Pack 500g / 1 Kg + Master Carton 15 Kg","moq":"500 Kg via Air Cargo / 10 Metric Tons via Sea FCL","shelfLife":"12 Bulan dalam penyimpanan dehumidified","colorTexture":"Cokelat Kemerahan Alami, Daging Kenyal, Aroma Harum Gurih"}',
  '45 Metrik Ton / Bulan',
  '45 Metric Tons / Month',
  '45 طن متري / شهر',
  '["HACCP Grade A","Health Certificate BKIPM","Halal BPJPH","US FDA Registered"]',
  '["Korea Selatan","Tiongkok","Taiwan","Jepang","Singapura"]',
  '/images/products/exp-ikan-b-1.png',
  '["/images/products/exp-ikan-b-1.png","/images/products/exp-ikan-b-2.png","/images/products/exp-ikan-b-3.png"]',
  'Cumi-cumi segar hasil tangkapan pancing sero yang langsung dibersihkan dan dikeringkan di bawah terik matahari pesisir. Menghasilkan rasa manis alami sari laut tanpa garam berlebih, sempurna untuk hidangan stir-fry oriental dan sambal cumi ekspor.',
  'Natural sun-dried squid and baby cuttlefish harvested from unpolluted Indonesian waters. Tender texture and natural sweetness.',
  'حبار مجفف طبيعياً بالشمس من المياه الإندونيسية النقية، نكهة بحرية غنية ولحم طري متماسك.',
  'Sun-Dried Squid & Baby Cuttlefish Grade A.',
  14.5,
  225000,
  500,
  'published',
  1,
  1,
  'Dried Squid & Baby Cuttlefish Supplier Indonesia',
  'Premium sun-dried squid exporter from Indonesia. Natural reddish-brown hue, low salt, ideal for Asian cuisine.',
  'https://www.driedseafoodglobal.com/products/sun-dried-squid-baby-cuttlefish',
  '/images/products/exp-ikan-b-1.png',
  '2026-01-10T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'exp-fish-maw',
  'Indonesian Premium Dried Fish Maw (Gelembung Ikan Gulama & Kakap)',
  'عوامات أسماك مجففة فاخرة (فيش ماو)',
  '印尼顶级金钱鳘鱼胶 / 纯天然花胶',
  'Pseudocienna crocea / Lates calcarifer',
  'Gelembung Ikan / Fish Maw Kering Kualitas Mewah',
  'indonesian-premium-dried-fish-maw',
  'DSG-PROD-004',
  'Gelembung Ikan / Fish Maw',
  '0305.72.00',
  'Merauke (Papua), Bagan Siapi-api (Riau), & Pontianak (Kalimantan Barat)',
  'Papua Coast, Riau & West Kalimantan, Indonesia',
  'ساحل بابوا ورياو وكاليمانتان الغربية، إندونيسيا',
  '{"grade":"Imperial First Grade (Thick Wall, Clean Amber Hue, Deep Collagen)","moisture":"Max 8.0%","packaging":"Gift Box Luxury Wood Case (1 Kg) / Air Cargo Carton (10 Kg)","moq":"25 Kg via Priority Air Freight / 100 Kg Konsolidasi","shelfLife":"5 Tahun (semakin lama semakin tinggi nilai gastronominya)","colorTexture":"Kuning Keemasan Jernih, Bebas Noda Darah, Sangat Tebal"}',
  '5 Metrik Ton / Bulan',
  '5 Metric Tons / Month',
  '5 طن متري / شهر',
  '["Health Certificate BKIPM","CITES Non-Endangered Verification","Halal BPJPH","Certificate of Origin (COO Form E)"]',
  '["Hong Kong (Sheung Wan Market)","Guangdong (Tiongkok)","Singapura","Taiwan","Kanada"]',
  '/images/products/exp-ikan-c-1.png',
  '["/images/products/exp-ikan-c-1.png","/images/products/exp-ikan-c-2.png"]',
  'Gelembung renang ikan air tawar dan laut dalam pilihan yang kaya kolagen murni. Disortir secara cermat satu per satu oleh spesialis kami untuk memenuhi standar perjamuan haute-cuisine Tiongkok, sup kesehatan bernilai tinggi, dan industri kecantikan.',
  'Imperial first-grade Indonesian dried fish maw rich in pure collagen. Meticulously hand-sorted for haute-cuisine Chinese banquet standards.',
  'حويصلات هوائية مجففة فاخرة لأسماك البحر العميقة غنية بالكولاجين النقي ومفرزة يدوياً وفق أعلى معايير الجودة العالمية.',
  'Imperial First Grade Dried Fish Maw.',
  180.0,
  2800000,
  25,
  'published',
  1,
  1,
  'Indonesian Dried Fish Maw Exporter (Hong Kong & China Form E)',
  'Premium Grade Dried Fish Maw from Merauke & Riau. High collagen thickness, CITES certified.',
  'https://www.driedseafoodglobal.com/products/indonesian-premium-dried-fish-maw',
  '/images/products/exp-ikan-c-1.png',
  '2026-01-10T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'exp-teripang',
  'Wild-Harvested Dried Sea Cucumber (Teripang Pasir & Gosok)',
  'خيار بحر مجفف بري ممتاز (رمال وأسود)',
  '野生深海干海参 / 白沙参 & 黑秃参',
  'Holothuria scabra / Holothuria nobilis',
  'Teripang Kering Super (Sandfish & Black Teatfish)',
  'wild-harvested-dried-sea-cucumber',
  'DSG-PROD-005',
  'Teripang & Hasil Laut Eksklusif',
  '0308.19.20',
  'Kepulauan Aru (Maluku), Kupang (NTT), & Kepulauan Selayar',
  'Aru Islands, East Nusa Tenggara & Selayar, Indonesia',
  'جزر أرو ونوسا تينجارا الشرقية، إندونيسيا',
  '{"grade":"Super Grade 1 (20-30 pcs/kg & 40-50 pcs/kg)","moisture":"Max 7.0% (Fully Sun-Dried & Smoked Cured)","packaging":"Vacuum Sealed Pack 1 Kg + Master Carton 20 Kg","moq":"50 Kg (Via Air Cargo Express) / 500 Kg Sea Cargo","shelfLife":"36 Bulan dalam wadah tertutup kering","colorTexture":"Hitam Keabuan Bersih, Bentuk Simetris, Tidak Retak"}',
  '8 Metrik Ton / Bulan',
  '8 Metric Tons / Month',
  '8 طن متري / شهر',
  '["Health Certificate BKIPM KKP","Sertifikat Bebas Logam Berat","Halal BPJPH","Form E COO"]',
  '["Hong Kong","Guangzhou (Tiongkok)","Singapura","Malaysia","Amerika Serikat"]',
  '/images/products/exp-ikan-d-1.png',
  '["/images/products/exp-ikan-d-1.png","/images/products/exp-ikan-d-2.png","/images/products/exp-ikan-d-3.png"]',
  'Teripang hasil tangkapan nelayan selam tradisional dari dasar laut terumbu karang yang bersih. Diproses melalui perebusan higienis dan pengasapan/penjemuran cermat, memiliki rasio pembesaran (expansion ratio) di atas 6x saat direhidrasi.',
  'Wild-harvested sea cucumber processed through clean traditional boiling and smoke curing. High expansion ratio upon rehydration.',
  'خيار بحر طبيعي مفرز بعناية ومجفف بالطرق الصحية المعتمدة، نسبة تمدد ممتازة عند إعادة الترطيب.',
  'Wild-Harvested Dried Sea Cucumber Grade 1.',
  120.0,
  1900000,
  50,
  'published',
  1,
  0,
  'Dried Sea Cucumber Exporter Indonesia',
  'Indonesian wild dried sandfish & black teatfish sea cucumber. Heavy expansion ratio, lab tested.',
  'https://www.driedseafoodglobal.com/products/wild-harvested-dried-sea-cucumber',
  '/images/products/exp-ikan-d-1.png',
  '2026-01-10T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'exp-udang-ebi',
  'Super Red Sun-Dried Prawns / Ebi Kering Pilihan',
  'روبيان مجفف بالشمس فائق الجودة (إيبي)',
  '特级纯日晒天然红虾米 / 海米',
  'Penaeus indicus / Metapenaeus affinis',
  'Ebi / Udang Kering Super Manis Gurih Alami',
  'super-red-sun-dried-prawns-ebi',
  'DSG-PROD-006',
  'Hasil Laut & Pangan',
  '0306.95.20',
  'Bagan Siapi-api (Riau), Juwana (Jawa Tengah), & Tarakan (Kalimantan Utara)',
  'Riau Coast, Juwana & Tarakan, Indonesia',
  'ساحل رياو وتاراكان، إندونيسيا',
  '{"grade":"Super Grade A (Warna Jingga Kemerahan Alami, Kulit Terkelupas Bersih)","moisture":"10% - 13% Max","packaging":"Food-Grade Polythene Bag (5 Kg) + 20 Kg Master Box","moq":"1.000 Kg (LCL) / 1 x 20ft FCL (15 Metric Tons)","shelfLife":"12 Bulan dalam suhu ruang kering sejuk","colorTexture":"Oranye Kemerahan, Aroma Harum Sedap, Bebas Zat Pewarna Buatan"}',
  '50 Metrik Ton / Bulan',
  '50 Metric Tons / Month',
  '50 طن متري / شهر',
  '["HACCP Grade A","Health Certificate BKIPM","SKP KKP RI","Halal BPJPH"]',
  '["Taiwan","Jepang","Singapura","Hong Kong","Uni Emirat Arab"]',
  '/images/products/exp-ikan-e-1.png',
  '["/images/products/exp-ikan-e-1.png","/images/products/exp-ikan-e-2.png","/images/products/exp-ikan-e-3.png"]',
  'Udang ebi kering kualitas nomor satu yang diproduksi dari udang segar tangkapan laut dangkal. Memiliki cita rasa manis gurih alami tanpa tambahan MSG, sangat cocok sebagai bumbu dasar saus XO oriental, dumpling, dan masakan gourmet.',
  'Number one grade sun-dried prawns made from wild coastal catch. Natural sweet umami flavor without synthetic additives.',
  'روبيان مجفف أحمر طبيعي فائق النكهة، خالي من أي مضافات صناعية أو ألوان كيميائية.',
  'Super Red Sun-Dried Prawns Grade A.',
  16.0,
  240000,
  1000,
  'published',
  1,
  1,
  'Dried Prawns & Ebi Exporter Indonesia',
  'Natural sun-dried red prawns from Riau and Java coast. Bright natural color, rich umami taste.',
  'https://www.driedseafoodglobal.com/products/super-red-sun-dried-prawns-ebi',
  '/images/products/exp-ikan-e-1.png',
  '2026-01-10T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'exp-tenggiri-kering',
  'Traditional Salted Spanish Mackerel Fillet (Tenggiri Papan Kering)',
  'فيليه سمك الماكريل الإسباني المملح المجفف',
  '特级传统腌制马鲛鱼片 / 咸鲅鱼柳',
  'Scomberomorus commerson',
  'Ikan Asin Tenggiri Batang & Papan Fillet Ekspor',
  'traditional-salted-spanish-mackerel-fillet',
  'DSG-PROD-007',
  'Ikan Asin Olahan Tradisional',
  '0305.59.30',
  'Laut Jawa, Lampung, & Selat Sunda',
  'Java Sea, Lampung & Sunda Strait, Indonesia',
  'بحر جاوة ومضيق سوندا، إندونيسيا',
  '{"grade":"Grade A Thick Cut Fillet (Bersih Tanpa Sisik, Bebas Tulang Utama)","moisture":"16% - 18% (Firm Dry Cured)","packaging":"Individual Shrink Wrap + 10 Kg Master Carton","moq":"1.000 Kg / 1 x 20ft Container (14 Metric Tons)","shelfLife":"10 Bulan dalam suhu kering terkontrol","colorTexture":"Daging Putih Mengkilap, Padat Gurih, Non-Formalin"}',
  '35 Metrik Ton / Bulan',
  '35 Metric Tons / Month',
  '35 طن متري / شهر',
  '["HACCP Grade A","Health Certificate KKP","Halal BPJPH"]',
  '["Singapura","Malaysia","Australia","Belanda","Kanada"]',
  '/images/products/exp-ikan-f-1.png',
  '["/images/products/exp-ikan-f-1.png","/images/products/exp-ikan-f-2.png","/images/products/exp-ikan-f-3.png","/images/products/exp-ikan-f-4.png"]',
  'Fillet ikan tenggiri segar yang diasinkan dengan garam laut murni bermutu tinggi. Dagingnya yang padat dan aroma sedap tanpa bau amis menyengat menjadikannya pilihan favorit hotel dan restoran seafood di Asia Tenggara.',
  'Thick cut salted Spanish mackerel fillet cured with pure sea salt. Firm white flesh with rich appetizing aroma.',
  'فيليه سمك الماكريل الإسباني المعالج بملح البحر النقي، لحم أبيض متماسك خالي من العظام الرئيسية.',
  'Salted Spanish Mackerel Thick Fillet.',
  11.5,
  175000,
  1000,
  'published',
  1,
  0,
  'Salted Spanish Mackerel Exporter Indonesia',
  'Thick salted mackerel fillets from Java Sea. Solid texture, rich aroma, 100% formalin-free.',
  'https://www.driedseafoodglobal.com/products/traditional-salted-spanish-mackerel-fillet',
  '/images/products/exp-ikan-f-1.png',
  '2026-01-10T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'exp-ikan-gabus',
  'Sun-Dried Snakehead Fish Fillet (Ikan Asin Gabus Kering Rawa)',
  'فيليه سمك رأس الأفعى المجفف بالشمس',
  '野生日晒黑鱼干柳 / 生鱼干片',
  'Channa striata',
  'Ikan Asin Gabus Pilihan & Bilis Kering Danau Toba',
  'sun-dried-snakehead-fish-fillet',
  'DSG-PROD-008',
  'Ikan Asin Olahan Tradisional',
  '0305.59.40',
  'Palembang (Sumatera Selatan), Banjarmasin (Kalimantan Selatan), & Danau Toba',
  'South Sumatra, South Kalimantan & Lake Toba, Indonesia',
  'سومطرة الجنوبية وكاليمانتان، إندونيسيا',
  '{"grade":"Grade A Butterfly Cut (Fillet Belah Kupu-Kupu Tanpa Kepala)","moisture":"12% - 14% Max (Kering Garing)","packaging":"Vacuum Bag 250g/500g + Master Box 15 Kg","moq":"500 Kg LCL / 10 Metric Tons FCL","shelfLife":"12 Bulan dalam penyimpanan sejuk","colorTexture":"Cokelat Terang Alami, Kering Renyah, Kaya Albumin"}',
  '30 Metrik Ton / Bulan',
  '30 Metric Tons / Month',
  '30 طن متري / شهر',
  '["HACCP Grade A","Health Certificate BKIPM","Halal BPJPH"]',
  '["Singapura","Malaysia","Taiwan","Jepang"]',
  '/images/products/exp-ikan-c-1.png',
  '["/images/products/exp-ikan-c-1.png"]',
  'Ikan gabus rawa segar yang terkenal akan kandungan protein dan albumin tinggi, dibelah butterfly dan dijemur hingga garing sempurna. Digemari para pemerhati gizi dan masakan tradisional di seluruh kawasan Asia Tenggara.',
  'Sun-dried wild snakehead fish butterfly fillet rich in albumin and natural protein. Perfectly dry and crisp.',
  'فيليه سمك غابوس المجفف الغني بالألبومين والبروتين الطبيعي، قطع فراشة مجففة بعناية فائقة.',
  'Sun-Dried Snakehead Fish Butterfly Fillet.',
  10.8,
  160000,
  500,
  'published',
  1,
  0,
  'Sun-Dried Snakehead Fish Exporter Indonesia',
  'High albumin dried snakehead fish fillet supplier from Indonesia. Butterfly cut, clean packaging.',
  'https://www.driedseafoodglobal.com/products/sun-dried-snakehead-fish-fillet',
  '/images/products/exp-ikan-c-1.png',
  '2026-01-10T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
);

-- 2. SEED ARTICLES
INSERT OR IGNORE INTO articles (
  id, title, title_en, title_ar, slug, excerpt, excerpt_en, excerpt_ar, content, content_en, content_ar,
  cover_image, author_name, author_role, author_avatar, category, tags, read_time, published_at,
  status, featured, seo_keywords, meta_title, meta_description, canonical_url, og_image_url, created_at, updated_at
) VALUES
(
  'blog-1',
  'Standar Mutu Ekspor Ikan Teri Nasi & Teri Medan ke Pasar Asia Timur & ASEAN',
  'Export Quality Standards of Indonesian White Anchovy to East Asia & ASEAN',
  'معايير جودة تصدير الأنشوجة البيضاء الإندونيسية إلى شرق آسيا والآسيان',
  'standar-mutu-ekspor-teri-nasi-teri-medan',
  'Kriteria ketat kadar air < 12%, warna putih bersih alami tanpa pemutih, dan protokol sortasi bertingkat untuk menembus pasar ritel premium di Taiwan, Hong Kong, dan Singapura.',
  'Strict criteria of moisture < 12%, natural ivory color without bleaching chemicals, and multi-tier sorting protocols to penetrate premium retail markets in Taiwan, Hong Kong, and Singapore.',
  'معايير صارمة لنسبة الرطوبة أقل من 12% ولون عاجي طبيعي دون مبيضات كيميائية لدخول الأسواق الراقية.',
  'Ikan teri nasi (Stolephorus commersonii) dan teri Medan merupakan salah satu komoditas perikanan kering khas Indonesia yang memiliki permintaan sangat tinggi di pasar internasional. Di Dried Seafood Global, kami menerapkan standar pengolahan pasca panen yang higienis untuk memastikan produk lolos inspeksi karantina di negara tujuan.

### 1. Seleksi Bahan Baku Segar
Ikan teri langsung diproses dalam waktu kurang dari 3 jam setelah mendarat di pelabuhan perikanan. Kesegaran ikan sangat menentukan warna alami dan keutuhan bentuk tubuh ikan saat dikeringkan.

### 2. Pengeringan Solar Dome Higienis
Kami meninggalkan metode penjemuran terbuka di tanah. Dengan sistem Solar Dome Dryer, suhu dan sirkulasi udara terkontrol sempurna tanpa resiko tercemar debu jalanan, lalat, maupun kotoran burung.

### 3. Jaminan Bebas Formalin & Uji Histamin
Setiap lot produksi diuji di laboratorium terakreditasi ISO 17025. Kami menjamin nol kandungan formalin, boraks, maupun pemutih sintetis, dengan kadar garam yang dapat disesuaikan dengan preferensi pembeli.',
  'White anchovy (Stolephorus commersonii) is one of Indonesia''s most demanded dried marine commodities internationally. We uphold rigorous hygienic processing standards to ensure quarantine compliance across all target ports.',
  'تعد الأنشوجة البيضاء الإندونيسية من أهم السلع البحرية المجففة المطلوبة عالمياً. نطبق أحدث المعايير الصحية لضمان الامتثال لجميع اشتراطات الحجر الصحي الدولية.',
  '/images/blog/standar-mutu-teri-nasi.png',
  'Dr. Rina Kusuma, S.Pi.',
  'Head of QA & Quarantine Compliance',
  'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
  'ekspor-pasar',
  '["Teri Nasi Super","Ekspor Ikan Kering","Standar Mutu","HACCP Grade A"]',
  '5 menit baca',
  '28 Februari 2026',
  'published',
  1,
  '["teri nasi indonesia","ikan teri medan","standar karantina ikan","dried anchovy supplier"]',
  'Standar Mutu Ekspor Ikan Teri Nasi & Teri Medan | Dried Seafood Global',
  'Pelajari kriteria ketat ekspor ikan teri nasi ke Taiwan, Hong Kong, dan Singapura: kadar air < 12%, bebas pemutih, dan sertifikasi HACCP.',
  'https://www.driedseafoodglobal.com/blog/standar-mutu-ekspor-teri-nasi-teri-medan',
  '/images/blog/standar-mutu-teri-nasi.png',
  '2026-02-28T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'blog-2',
  'Panduan Karantina Ikan KKP & Pengurusan Health Certificate (HC) Ekspor',
  'Indonesian Fishery Quarantine Guide & Health Certificate Processing',
  'دليل الحجر الصحي للأسماك وإصدار الشهادات الصحية للتصدير من إندونيسيا',
  'panduan-karantina-ikan-health-certificate-ekspor',
  'Langkah taktis pengurusan dokumen resmi Badan Karantina Ikan KKP (BKIPM), pengujian organoleptik, dan penerbitan Certificate of Origin untuk tarif preferensi 0%.',
  'Tactical steps for obtaining official BKIPM Fishery Quarantine documents, organoleptic testing, and Certificate of Origin issuance for 0% preferential tariffs.',
  'خطوات عملية لإصدار وثائق الحجر الصحي الرسمية من BKIPM واختبارات الجودة وشهادات المنشأ للرسوم الجمركية التفضيلية.',
  'Menghadapi regulasi ketat kepabeanan internasional, kelengkapan sertifikat karantina perikanan adalah syarat mutlak agar barang tidak tertahan di pelabuhan masuk (port of entry).

### Dokumen Kunci yang Wajib Dimiliki:
* **Health Certificate (HC) BKIPM:** Membuktikan produk ikan kering aman dari cemaran mikroba berbahaya dan layak konsumsi.
* **Certificate of Analysis (COA):** Hasil uji lab independen atas parameter kadar air, histamin, dan bebas bahan pengawet ilegal.
* **COO Form E & Form D:** Fasilitas bea masuk nol persen bagi importir di Tiongkok dan negara-negara ASEAN.

Hubungi tim spesialis ekspor Dried Seafood Global untuk mendapatkan konsultasi regulasi kepabeanan produk perikanan di negara Anda.',
  'Compliance with international seafood quarantine regulations is mandatory. Essential documents include BKIPM Health Certificate, Certificate of Analysis, and COO Form E/D.',
  'يعد الامتثال لاشتراطات الحجر الصحي الدولي للأسماك أمراً حيوياً لتفادي أي تأخير جمركي. تشمل الوثائق الأساسية الشهادة الصحية وشهادة التحليل المخبري وشهادة المنشأ.',
  '/images/blog/panduan-karantina-ikan.png',
  'Ir. H. Bambang Priyono',
  'CEO & Founder',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
  'teknologi-pengolahan',
  '["Health Certificate","BKIPM KKP","Dokumen Ekspor","Kepatuhan Regulasi"]',
  '6 menit baca',
  '15 Februari 2026',
  'published',
  0,
  '["health certificate ikan","karantina perikanan","ekspor hasil laut","Form E Tiongkok"]',
  'Panduan Karantina Ikan KKP & Health Certificate Ekspor | Dried Seafood Global',
  'Panduan lengkap prosedur karantina ikan KKP, penerbitan Health Certificate, COA ISO 17025, dan COO Form E untuk ekspor perikanan lancar.',
  'https://www.driedseafoodglobal.com/blog/panduan-karantina-ikan-health-certificate-ekspor',
  '/images/blog/panduan-karantina-ikan.png',
  '2026-02-15T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'blog-3',
  'Gelembung Ikan (Fish Maw) Indonesia: Nilai Ekonomis dan Standar Grading Ekspor',
  'Indonesian Fish Maw: Economic Value and Export Grading Standards',
  'عوامات الأسماك الإندونيسية (فيش ماو): القيمة الاقتصادية ومعايير التصنيف',
  'gelembung-ikan-fish-maw-indonesia-grading-ekspor',
  'Mengenal komoditas laut eksklusif bernilai tinggi, karakteristik Fish Maw Gulama dan Kakap, serta metode pengeringan alami untuk menjaga kandungan kolagen.',
  'Discover the luxury dried marine commodity, characteristics of Croaker & Seabass Fish Maw, and natural curing methods preserving pure collagen.',
  'تعرف على عوامات الأسماك المجففة الفاخرة وخصائصها الغنية بالكولاجين وطرق التجفيف الطبيعية المعتمدة.',
  'Gelembung renang ikan atau dikenal secara internasional sebagai Fish Maw merupakan komoditas laut kering premium dengan nilai jual tinggi di pasar Tiongkok Raya dan Asia Timur. 

Kualitas Fish Maw dinilai berdasarkan ketebalan dinding, kejernihan serat saat diterawang cahaya, dan ketiadaan bintik darah. Dried Seafood Global menyediakan Fish Maw kualitas ekspor dengan penyortiran manual oleh tenaga ahli berpengalaman puluhan tahun.',
  'Fish Maw is a premier luxury dried seafood commodity with high commercial demand across Greater China and East Asia. Evaluated by wall thickness and pure amber transparency.',
  'تعتبر حويصلات الأسماك الهوائية سلعة بحرية فاخرة عالية القيمة في الأسواق الآسيوية، تقاس جودتها بالسماكة والنقاء وخلوها من الشوائب.',
  '/images/blog/gelembung-ikan-fish-maw.png',
  'Kenneth Chen',
  'Director of Asian Seafood Trade',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
  'regulasi-sertifikasi',
  '["Fish Maw","Gelembung Ikan","Komoditas Mewah","Perdagangan Asia"]',
  '4 menit baca',
  '04 Februari 2026',
  'published',
  0,
  '["supplier fish maw","gelembung ikan ekspor","fish maw indonesia","isinglass"]',
  'Gelembung Ikan (Fish Maw) Indonesia: Nilai Ekonomis & Grading Ekspor',
  'Panduan grading gelembung ikan (fish maw) Indonesia: ketebalan, kejernihan serat amber, dan verifikasi CITES untuk pasar Hong Kong dan Tiongkok.',
  'https://www.driedseafoodglobal.com/blog/gelembung-ikan-fish-maw-indonesia-grading-ekspor',
  '/images/blog/gelembung-ikan-fish-maw.png',
  '2026-02-04T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'blog-4',
  'Pemberdayaan Nelayan Tradisional & Standar Keberlanjutan Hasil Laut Kering',
  'Empowering Traditional Fishermen & Sustainable Dried Seafood Standards',
  'تمكين الصيادين التقليديين ومعايير استدامة المأكولات البحرية المجففة',
  'pemberdayaan-nelayan-dan-keberlanjutan-seafood',
  'Komitmen kemitraan rantai pasok maritim yang adil bersama ribuan keluarga nelayan tangkap di pesisir Sumatera, Jawa, dan Sulawesi.',
  'Our fair supply chain partnership commitment with thousands of traditional coastal fishing families across Sumatra, Java, and Sulawesi.',
  'التزامنا بالشراكة العادلة في سلاسل الإمداد مع آلاف عائلات الصيادين التقليديين في السواحل الإندونيسية.',
  'Keberlanjutan pasokan ikan kering bermutu tinggi berakar dari kesejahteraan para nelayan mitra. Kami memberikan edukasi pengolahan higienis di atas perahu, penyediaan garam laut murni bersertifikat, dan kepastian harga beli yang stabil demi memutus rantai tengkulak yang merugikan.',
  'Sustainable supply of premium dried fish stems from the prosperity of partner fishermen. We provide hygiene training on boats, pure certified sea salt, and fair floor pricing.',
  'إن استدامة جودة منتجاتنا تبدأ من دعم صيادينا المحليين بتدريبهم على الاشتراطات الصحية وتقديم أسعار عادلة ومستقرة.',
  '/images/blog/pemberdayaan-nelayan-dan-keberlanjutan-seafood.png',
  'Hendra Tanudjaja, S.T.',
  'Director of Marine Logistics',
  'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
  'nelayan-keberlanjutan',
  '["Pemberdayaan Nelayan","Fair Trade","Keberlanjutan","Pesisir Indonesia"]',
  '5 menit baca',
  '22 Januari 2026',
  'published',
  0,
  '["nelayan indonesia","rantai pasok ikan","sustainable seafood","tanggung jawab sosial"]',
  'Pemberdayaan Nelayan & Keberlanjutan Seafood Kering Indonesia',
  'Komitmen ESG Dried Seafood Global memberdayakan nelayan pesisir dengan kapal tangkap ramah lingkungan dan sistem fair trade.',
  'https://www.driedseafoodglobal.com/blog/pemberdayaan-nelayan-dan-keberlanjutan-seafood',
  '/images/blog/pemberdayaan-nelayan-dan-keberlanjutan-seafood.png',
  '2026-01-22T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
);

-- 3. SEED ARTICLE COMMENTS
INSERT OR IGNORE INTO article_comments (
  id, article_id, author, email, content, created_at
) VALUES (
  'c-1',
  'blog-1',
  'Lawrence Wong (Procurement Manager - Sing Lun Seafood)',
  'wong@singlunmarine.com',
  'Kualitas teri nasi dari Dried Seafood Global sangat luar biasa. Putih bersih, renyah saat digoreng, dan packaging vakumnya sangat rapi untuk etalase supermarket kami di Jurong.',
  '2026-03-01T00:00:00.000Z'
);

-- 4. SEED INQUIRIES
INSERT OR IGNORE INTO inquiries (
  id, name, contact_person, email, phone, company_name, inquiry_type, commodity,
  destination_country, origin_country, estimated_weight, volume_tons, shipping_terms,
  message, status, reply_notes, ip_location, ssl_encrypted, submitted_at, created_at, updated_at
) VALUES 
(
  'inq-101',
  'Budi Hartono',
  'Budi Hartono',
  'budi.hartono@manufacturing-corp.com',
  '+62 812 3456 7890',
  'PT Nusantara Auto Parts Prima',
  'Permintaan Penawaran (RFQ)',
  'Ikan Teri Nasi Super Putih Grade AAA',
  'DE',
  'ID',
  48000,
  48.0,
  'CIF Hamburg',
  'Kami membutuhkan penawaran pengiriman rutin 4x40ft FCL komponen otomotif dari Pelabuhan Tanjung Priok ke Hamburg Port setiap bulan.',
  'new',
  NULL,
  'Jakarta, Indonesia',
  1,
  '2026-09-07 14:22:00',
  '2026-09-07T14:22:00.000Z',
  '2026-09-07T14:22:00.000Z'
),
(
  'inq-102',
  'Eleanor Vance',
  'Eleanor Vance',
  'e.vance@vance-pharma.ch',
  '+41 44 211 4400',
  'Vance BioPharma Ltd',
  'Dukungan Logistik',
  'Fish Maw / Gelembung Ikan Kering Premium',
  'SG',
  'CH',
  2500,
  2.5,
  'Air Freight Priority',
  'Mencari mitra pergudangan cold chain bersertifikat GDP di Singapura dan Jakarta untuk produk biofarma suhu 2-8°C.',
  'reviewed',
  'Sudah dijadwalkan Zoom meeting teknis dengan tim Pharma Logistics pada 10 September.',
  'Zurich, Switzerland',
  1,
  '2026-09-06 09:15:00',
  '2026-09-06T09:15:00.000Z',
  '2026-09-06T09:15:00.000Z'
);

-- 5. SEED GALLERY
INSERT OR IGNORE INTO gallery (
  id, title, title_en, title_ar, category, image_url, location, location_en, location_ar, date, description, description_en, description_ar, tags, dimensions, created_at, updated_at
) VALUES
(
  'gal-1',
  'Sentra Pengeringan & Sortasi Teri Nasi Super Pilihan',
  'Super White Anchovy Drying & Sorting Facility',
  'مركز تجفيف وفرز الأنشوجة البيضاء الفاخرة',
  'processing',
  '/images/gallery/surtir-teri-nasi-super.png',
  'Sentra Pengolahan Muara Baru & Belawan',
  'Muara Baru & Belawan Processing Hubs',
  'مركز موارا بارو وبيلاوان للمعالجة',
  '15 Agustus 2025',
  'Proses pemilihan dan sortasi ikan teri nasi putih super grade tanpa bahan pengawet kimia dengan penjemuran higienis di atas rak stainless steel mesh.',
  'Manual sorting and hygienic drying of super white anchovy on food-grade stainless steel mesh without chemical preservatives.',
  'عملية فرز وتجفيف الأنشوجة البيضاء على رفوف الفولاذ المقاوم للصدأ بدون أي مواد حافظة كيميائية.',
  '["Teri Nasi Super","Higiene Pangan","Sortasi Manual","Grade A"]',
  '1200x800',
  '2025-08-15T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-2',
  'Fasilitas Dehumidified Storage Berstandar HACCP KKP',
  'HACCP Standard Dehumidified Storage Facility',
  'مستودعات مكيفة ومضبوطة الرطوبة وفق معايير الهاسب',
  'storage',
  'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
  'Kawasan Industri Perikanan Marunda, Jakarta Utara',
  'Marunda Fishery Industrial Zone, North Jakarta',
  'منطقة ماروندا الصناعية للأسماك، شمال جاكرتا',
  '10 Juli 2025',
  'Gudang penyimpanan kering berkelembaban terkontrol (RH < 55%) seluas 18.500 m² yang melindungi produk dari jamur dan menjaga aroma khas hasil laut.',
  'Humidity-controlled storage warehouse (RH < 55%) protecting dried marine products from moisture and preserving aroma.',
  'مستودع تخزين جاف مضبوط الرطوبة (أقل من 55%) لحماية المنتجات البحرية وضمان جودتها العالية.',
  '["Dehumidified Storage","HACCP Grade A","Bebas Hama","Steril"]',
  '1200x800',
  '2025-07-10T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-3',
  'Grading Gelembung Ikan (Fish Maw) & Teripang Kering Super',
  'Premium Dried Fish Maw & Sea Cucumber Grading',
  'فرز وتصنيف عوامات الأسماك وخيار البحر المجفف',
  'commodities',
  '/images/gallery/grading-fish-maw.png',
  'Fasilitas Ekspor Premium Muara Baru, Jakarta',
  'Muara Baru Premium Export Facility, Jakarta',
  'مرفق التصدير الفاخر في موارا بارو، جاكرتا',
  '02 Mei 2025',
  'Pemeriksaan ketebalan, kejernihan, dan kadar air gelembung ikan (fish maw) kelas premium untuk pasar restoran mewah dan pengobatan tradisional Hong Kong.',
  'Thickness, transparency, and moisture grading of premier fish maw for luxury restaurants and Asian herbal markets.',
  'فحص السماكة والنقاء والرطوبة لحويصلات الأسماك الفاخرة لأسواق هونغ كونغ والمطاعم الراقية.',
  '["Fish Maw","Gelembung Ikan","Luxury Seafood","Hong Kong Trade"]',
  '1200x800',
  '2025-05-02T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-4',
  'Pemuatan Kontainer Ekspor Ikan Asin Jambal Roti & Tenggiri',
  'FCL Container Loading for Export of Salted Catfish & Mackerel',
  'تحميل حاويات التصدير الكاملة لسمك جامبال وماكريل مملح',
  'shipping',
  'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1200&q=80',
  'Terminal Petikemas Tanjung Priok Jakarta',
  'Tanjung Priok Container Terminal, Jakarta',
  'محطة حاويات تانجونغ بريوك، جاكرتا',
  '28 Juni 2025',
  'Pemuatan 1 x 40ft High Cube Container berisi ikan asin jambal roti dan tenggiri kering dengan moisture absorber desiccant untuk tujuan Los Angeles, USA.',
  'Loading a 40ft High Cube Container of dried salted catfish and mackerel with moisture desiccants bound for Los Angeles, USA.',
  'تحميل حاوية 40 قدم عالية السعة محملة بالأسماك المجففة والمملحة مع مجففات امتصاص الرطوبة متجهة إلى لوس أنجلوس.',
  '["Ekspor FCL","Tanjung Priok","Moisture Absorber","USA Trade"]',
  '1200x800',
  '2025-06-28T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-5',
  'Ruang Pengemasan Higienis Vacuum Seal & Retail Pouch',
  'Hygienic Vacuum Sealing & Retail Packaging Cleanroom',
  'غرفة التغليف الصحي المفرغ من الهواء والعبوات الاستهلاكية',
  'storage',
  'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=1200&q=80',
  'Sentra Produksi & Pengemasan Marunda',
  'Marunda Packaging Center',
  'مركز التعبئة والتغليف في ماروندا',
  '18 April 2025',
  'Area pengemasan steril kedap udara dengan mesin continuous band sealer dan automatic vacuum packaging untuk pesanan private label supermarket diaspora.',
  'Airtight sterile cleanroom packaging with continuous band sealers and automatic vacuum packaging for private label overseas supermarkets.',
  'غرفة تغليف معقمة مزودة بآلات إغلاق وسحب هواء آلية للعلامات التجارية الخاصة وسلاسل السوبرماركت.',
  '["Vacuum Packaging","Private Label","Kemasan Ritel","Food Grade"]',
  '1200x800',
  '2025-04-18T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-6',
  'Uji Laboratorium Bebas Formalin & Uji Histamin Karantina',
  'Formalin-Free Laboratory Testing & Quarantine Histamine Screening',
  'الفحص المخبري للتأكد من خلو المنتجات من الفورمالين ومراقبة الهستامين',
  'storage',
  '/images/gallery/lab-testing-formalin.png',
  'Laboratorium Mutu Terpadu Dried Seafood Global',
  'Dried Seafood Global Integrated QA Lab',
  'مختبر الجودة المتكامل لـ Dried Seafood Global',
  '04 September 2025',
  'Pengujian ketat setiap batch untuk menjamin 0% formalin, kadar air < 14%, serta kadar garam yang presisi sebelum penerbitan Health Certificate resmi.',
  'Strict batch testing guaranteeing 0% formalin, moisture < 14%, and precise salinity prior to Health Certificate issuance.',
  'فحص صارم لكل دفعة إنتاج لضمان خلوها بنسبة 100% من الفورمالين ومطابقة نسبة الملوحة والرطوبة.',
  '["Lab Testing","Zero Formalin","BKIPM KKP","Health Certificate"]',
  '1200x800',
  '2025-09-04T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-7',
  'Teknologi Pengeringan Solar Dome Dryer Higienis',
  'Hygienic Solar Dome Dryer Technology',
  'تقنية التجفيف بالطاقة الشمسية داخل القبة النظيفة (سولار دوم)',
  'processing',
  '/images/gallery/solar-dome-dryer.png',
  'Sentra Nelayan Binaan Pantura Jawa Tengah',
  'Central Java Coastal Fishermen Center',
  'مركز صيادي الساحل الشمالي، جاوة الوسطى',
  '12 Januari 2026',
  'Kubah pengering bertenaga surya tertutup yang melindungi ikan teri dan cumi dari debu, lalat, dan kontaminasi udara luar dengan sirkulasi panas merata.',
  'Enclosed solar-powered drying dome protecting anchovies and squid from dust, flies, and air pollutants with even thermal circulation.',
  'قبة تجفيف بالطاقة الشمسية مغلقة تحمي الأسماك والحبار من الغبار والملوثات وتضمن حرارة متوازنة.',
  '["Solar Dome","Higiene Pengeringan","Bebas Lalat","Pemberdayaan Nelayan"]',
  '1200x800',
  '2026-01-12T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-8',
  'Pengiriman Kargo Udara Kilat Prioritas ke Bandara Internasional',
  'Priority Air Cargo Express Shipping to Global Hubs',
  'شحن جوي سريع وأولوية إلى المطارات الدولية الرئيسية',
  'shipping',
  'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=1200&q=80',
  'Area Kargo Bandara Soekarno-Hatta (CGK)',
  'Soekarno-Hatta Int''l Airport Cargo Area (CGK)',
  'منطقة الشحن بمطار سوكارنو هاتا الدولي',
  '20 Februari 2026',
  'Pemberangkatan kargo udara berpendingin dan segel tamper-evident untuk komoditas fish maw dan ebi kualitas super ke Changi Singapura dan Hong Kong.',
  'Departure of temperature-controlled air cargo with tamper-evident security seals for luxury fish maw and dried prawns to Singapore Changi and Hong Kong.',
  'شحنات جوية ذات أختام أمنية عالية لمنتجات الفيش ماو والروبيان المجفف الفاخر إلى مطارات سنغافورة وهونغ كونغ.',
  '["Air Cargo","Express Transit","Fish Maw","Seafood Ekspor"]',
  '1200x800',
  '2026-02-20T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-9',
  'Kemitraan Nelayan Pesisir Tangkap Ramah Lingkungan',
  'Sustainable Coastal Fishermen Partnership',
  'شراكة الصيد الساحلي المستدام والصديق للبيئة',
  'sustainability',
  '/images/gallery/nelayan-tangkap-ramah-lingkungan.png',
  'Sentra Nelayan Pesisir Pangandaran & Cilacap',
  'Pangandaran & Cilacap Coastal Fishing Centers',
  'مراكز الصيد الساحلي في بانغانداران وتشيلاكاب',
  '18 Oktober 2025',
  'Pemberdayaan 1.200+ nelayan tradisional dengan kapal tangkap ramah lingkungan, jaring non-trawl, dan jaminan pembelian hasil tangkap ikan segar dengan harga adil.',
  'Empowering 1,200+ artisanal fishermen with eco-friendly non-trawl nets and guaranteed fair-trade fresh fish procurement.',
  'تمكين أكثر من 1200 صياد تقليدي بشباك صديقة للبيئة غير جارفة مع ضمان شراء المحصول بأسعار عادلة ومجزية.',
  '["Fair Trade","Nelayan Tradisional","Non-Trawl","ESG Fisheries"]',
  '1200x800',
  '2025-10-18T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-10',
  'Sortasi & Pembersihan Cumi Kering Sero Telur Utuh',
  'Whole Roe Squid Grading & Natural Sea Salt Cleansing',
  'فرز وتنظيف حبار السيرو المحمل بالبيض بملح البحر الطبيعي',
  'commodities',
  '/images/gallery/sortasi-cumi-sero.png',
  'Sentra Pemrosesan Cumi Muara Angke, Jakarta',
  'Muara Angke Squid Processing Center, Jakarta',
  'مركز معالجة الحبار في موارا أنغكي، جاكرتا',
  '05 November 2025',
  'Pembersihan manual cumi sero telur dengan air garam laut murni sebelum penjemuran pada dome tertutup untuk menjaga warna putih kemerahan alami.',
  'Manual cleaning of whole egg roe squid with pure seawater brine before solar dome curing to maintain natural reddish-white hue.',
  'تنظيف يدوي لحبار السيرو المحمل بالبيض بماء البحر النقي قبل التجفيف بالقبة الشمسية للحفاظ على لونه الطبيعي المميز.',
  '["Cumi Sero","Squid Trade","Alami Tanpa Pemutih","Grade AAA"]',
  '1200x800',
  '2025-11-05T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-11',
  'Inspeksi Petugas Karantina Ikan BKIPM KKP untuk Health Certificate',
  'BKIPM Fishery Quarantine Official Inspection for Health Certificate',
  'تفتيش مسؤولي الحجر الصحي للأسماك لإصدار الشهادات الصحية الرسمية',
  'processing',
  '/images/gallery/inspeksi-karantina-bkipm.png',
  'Stasiun Karantina Ikan Pengendalian Mutu (SKIPM) Tanjung Priok',
  'SKIPM Fishery Quarantine Station, Tanjung Priok Port',
  'محطة الحجر الصحي لمراقبة الجودة، ميناء تانجونغ بريوك',
  '14 Desember 2025',
  'Pemeriksaan fisik dan organoleptik oleh inspektur karantina resmi KKP untuk memastikan kepatuhan standar SPS (Sanitary and Phytosanitary) negara tujuan.',
  'Physical and organoleptic verification by government quarantine inspectors ensuring strict Sanitary and Phytosanitary (SPS) compliance.',
  'فحص حسي ومخبري دقيق من قبل مفتشي الحجر الصحي الحكومي لضمان الالتزام بمعايير الصحة والصحة النباتية الدولية.',
  '["Inspeksi Karantina","Health Certificate","KKP RI","SPS Standards"]',
  '1200x800',
  '2025-12-14T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
),
(
  'gal-12',
  'Program Kemitraan UMKM Nelayan Perempuan Pengolah Ikan Asin',
  'Coastal Women Fisherfolk Partnership Program',
  'برنامج تمكين رائدات الأعمال والنساء في مجتمعات الصيد الساحلية',
  'sustainability',
  '/images/gallery/kemitraan-umkm-nelayan-perempuan.png',
  'Koperasi Nelayan Pesisir Belawan, Sumatera Utara',
  'Belawan Coastal Fishermen Cooperative, North Sumatra',
  'تعاونية صيادي الساحل في بيلاوان، سومطرة الشمالية',
  '22 Januari 2026',
  'Pelatihan standar sanitasi, penggunaan Solar Dome, dan teknik pembelahan ikan asin peda & jambal yang higienis untuk kelompok ibu nelayan pesisir.',
  'Sanitation standards, solar dome drying techniques, and hygienic fish filleting training for coastal women fisherfolk associations.',
  'تدريب نساء مجتمعات الصيد على معايير النظافة واستخدام القباب الشمسية وتقنيات تقطيع الأسماك الصحية.',
  '["Pemberdayaan Perempuan","Koperasi Nelayan","Pelatihan Higiene","Dampak Sosial"]',
  '1200x800',
  '2026-01-22T00:00:00.000Z',
  '2026-03-01T00:00:00.000Z'
);

-- 6. SEED SEO SETTINGS
INSERT OR IGNORE INTO seo_settings (
  id, meta_title, site_title, meta_description, keywords, focus_keywords, canonical_url,
  og_image_url, author, structured_data_type, robots_index, robots_follow, sitemap_count,
  ssl_grade, google_search_console_key, google_analytics_id, google_tag_manager_id,
  google_merchant_center_id, google_business_profile_url, updated_at
) VALUES (
  'default',
  'Dried Seafood Global - Eksportir Resmi Produk Ikan & Hasil Laut Khas Indonesia',
  'Dried Seafood Global | Eksportir Ikan Asin Higienis Demak Indonesia',
  'Eksportir resmi terpercaya produk ikan asin, teri nasi super, cumi kering, gelembung ikan (fish maw), dan hasil laut Nusantara berstandar HACCP dan KKP ke 28+ negara.',
  '["eksportir ikan asin","dried seafood indonesia","salted fish exporter","ikan jambal roti","teri nasi medan","solar dome dryer","haccp seafood"]',
  '["dried seafood global","ikan asin indonesia","teri medan indonesia","cumi kering indonesia","supplier fish maw","indonesian dried fish supplier","ikan asin jambal roti"]',
  'https://www.driedseafoodglobal.com/',
  'https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=1200&q=80',
  'PT Global Maritim Samudera',
  'Corporation',
  1,
  1,
  32,
  'A+',
  '',
  '',
  '',
  '',
  'https://maps.google.com/?q=Kawasan+Industri+Maritim+Muara+Baru+Jakarta+Utara',
  '2026-03-01T00:00:00.000Z'
);
